#pragma once
//===========================================================================
//========================== DO NOT EDIT THIS FILE ==========================
//===========================================================================

#define CONFIGURATION_H_VERSION 020008
#define PRUSA_SKR_CONFIGURATION_VERSION 20210129

//===========================================================================
//=========================== Predefined Configs ============================
//===========================================================================

/**
 * Chris' Bear/Caribou Configs
 *
 * Options:  1: Bearmera       5: Grey Bear
 *           2: Beetlejuice    6: Purple Bear
 *           3: Caribou 320    7: Slimer
 *           4: Elvira
 */
//#define PRUSA_SKR_CONF_CHRIS 1

// Keith's Bear Config
//#define PRUSA_SKR_CONF_AILUROS

//===========================================================================
//============================== Printer Name ===============================
//===========================================================================

// "Turbo" moniker is not added because it exceeds the status area's 20 chararcter
// limit due to "Printer Name" + " Ready."

#ifdef PRUSA_SKR_CUSTOM_NAME
  #define CUSTOM_MACHINE_NAME PRUSA_SKR_CUSTOM_NAME
#elif PRUSA_SKR_FRAME == 1 || PRUSA_SKR_FRAME == 2
  #define CUSTOM_MACHINE_NAME "SKR Bear"
#elif PRUSA_SKR_FRAME == 3 || PRUSA_SKR_FRAME == 4 || PRUSA_SKR_FRAME == 5
  #define CUSTOM_MACHINE_NAME "SKR Caribou"
#endif

//===========================================================================
//=========================== Printer/Frame Type ============================
//===========================================================================

// Prusa Bear frame (210mm Z) is enabled by default.

/**
 * Options:  Bear Frames                Caribou Frames
 *           1: Bear       (210mm Z)    3: Caribou 220  (220mm Z)
 *           2: Tall Bear  (320mm Z)    4: Caribou 320  (320mm Z)
 *                                      5: Caribou 420  (420mm Z)
 */
#if !defined(PRUSA_SKR_FRAME) || (PRUSA_SKR_FRAME < 1 || PRUSA_SKR_FRAME > 5)
  #error "PRUSA_SKR_FRAME is invalid or not defined."
#elif PRUSA_SKR_FRAME == 1 // Bear
  #define Z_MAX_POS 210
#elif PRUSA_SKR_FRAME == 3 // Caribou 220
  #define Z_MAX_POS 220
#elif PRUSA_SKR_FRAME == 4 || PRUSA_SKR_FRAME == 2 // Tall Bear or Caribou 320
  #define Z_MAX_POS 320
#elif PRUSA_SKR_FRAME == 5 // Caribou 420
  #define Z_MAX_POS 420
#endif

//===========================================================================
//=============================== Motherboard ===============================
//===========================================================================

// SKR 1.4 is enabled by default.

/**
 * Options:  1: BigTreeTech SKR 1.4        (LPC1768)
 *           2: BigTreeTech SKR 1.4 Turbo  (LPC1769)
 *           3: BigTreeTech BTT002 1.0     (STM32F4)
 */
#if !defined(PRUSA_SKR_MOTHERBOARD) || (PRUSA_SKR_MOTHERBOARD < 1 || PRUSA_SKR_MOTHERBOARD > 2)
  #error "PRUSA_SKR_MOTHERBOARD is invalid or not defined."
#elif PRUSA_SKR_MOTHERBOARD == 1
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4
#elif PRUSA_SKR_MOTHERBOARD == 2
  #define MOTHERBOARD BOARD_BTT_SKR_V1_4_TURBO
#elif PRUSA_SKR_MOTHERBOARD == 3 // Coming soon ;-)
  //#define MOTHERBOARD BOARD_BTT_BTT002_V1_0
#endif

//===========================================================================
//============================= Stepper Motors ==============================
//===========================================================================

/**
 * Extruder Stepper Motor
 *
 * Stock 1.8° extruder stepper is enabled by default.
 *
 * Options:  1: Stock 1.8°
 *           2: Bondtech/Motech 1.8° pancake
 *           3: LDO 0.9° pancake
 *           4: LDO planetary
 */
#if !defined(PRUSA_SKR_E_STEPPER) || (PRUSA_SKR_E_STEPPER < 1 || PRUSA_SKR_E_STEPPER > 4)
  #error "PRUSA_SKR_E_STEPPER is invalid or not defined."
#elif (PRUSA_SKR_E_STEPPER == 1) && (PRUSA_SKR_EXTRUDER == 3 || PRUSA_SKR_EXTRUDER == 4)
  #error "Stock 1.8° stepper on a BMG extruder is not supported."
#elif (PRUSA_SKR_E_STEPPER == 2 || PRUSA_SKR_E_STEPPER == 3) && (PRUSA_SKR_EXTRUDER == 1 || PRUSA_SKR_EXTRUDER == 2)
  #error "Pancake stepper on a Bear extruder is not supported."
#elif (PRUSA_SKR_E_STEPPER == 4) && (PRUSA_SKR_EXTRUDER == 3 || PRUSA_SKR_EXTRUDER == 4)
  #error "Planetary stepper on a BMG extruder is not supported."
#elif PRUSA_SKR_E_STEPPER == 1 // Stock 1.8°

  #if DISABLED(PRUSA_SKR_INVERT_E_DIR)
    #define INVERT_E0_DIR                  false
  #else
    #define INVERT_E0_DIR                   true
  #endif

  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  280
  #define E0_CURRENT                         550
  #define E0_MICROSTEPS                       32
#elif PRUSA_SKR_E_STEPPER == 2 // Bondtech/Motech 1.8° pancake
  #if DISABLED(PRUSA_SKR_INVERT_E_DIR)
    #define INVERT_E0_DIR                   true
  #else
    #define INVERT_E0_DIR                  false
  #endif

  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  830
  #define E0_CURRENT                         550
  #define E0_MICROSTEPS                       32
#elif PRUSA_SKR_E_STEPPER == 3 // LDO 0.9° pancake
  #if DISABLED(PRUSA_SKR_INVERT_E_DIR)
    #define INVERT_E0_DIR                   true
  #else
    #define INVERT_E0_DIR                  false
  #endif

  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  830
  #define E0_CURRENT                         800
  #define E0_MICROSTEPS                       16
#elif PRUSA_SKR_E_STEPPER == 4 // LDO planetary
  #if DISABLED(PRUSA_SKR_INVERT_E_DIR)
    #define INVERT_E0_DIR                   true
  #else
    #define INVERT_E0_DIR                  false
  #endif

  #define PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT  980
  #define E0_CURRENT                         650
  #define E0_MICROSTEPS                       32
#endif

/**
 * X/Y Stepper Motors
 *
 * Stock 1.8° X/Y steppers are enabled by default.
 *
 * Options:  1: Stock 1.8° X/Y
 *           2: LDO 0.9° X/Y
 *           3: Moons 0.9° X/Y
 */
#if !defined(PRUSA_SKR_XY_STEPPERS) || (PRUSA_SKR_XY_STEPPERS < 1 || PRUSA_SKR_XY_STEPPERS > 3)
  #error "PRUSA_SKR_XY_STEPPERS is invalid or not defined."
#elif PRUSA_SKR_XY_STEPPERS == 1 // Stock 1.8° X/Y
  #define DEFAULT_AXIS_STEPS_PER_UNIT  { 100, 100, 400, (PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT) }
  #define X_CURRENT                500
  #define X_CURRENT_HOME           200
  #define Y_CURRENT                600
  #define Y_CURRENT_HOME           250

  // StallGuard settings
  #ifdef PRUSA_SKR_X_STALL_SENSITIVITY
    #define X_STALL_SENSITIVITY PRUSA_SKR_X_STALL_SENSITIVITY
  #else
    #define X_STALL_SENSITIVITY     90
  #endif
  #ifdef PRUSA_SKR_Y_STALL_SENSITIVITY
    #define Y_STALL_SENSITIVITY PRUSA_SKR_Y_STALL_SENSITIVITY
  #else
    #define Y_STALL_SENSITIVITY    100
  #endif

#elif PRUSA_SKR_XY_STEPPERS == 2 || PRUSA_SKR_XY_STEPPERS == 3 // LDO or Moons 0.9° X/Y
  #define DEFAULT_AXIS_STEPS_PER_UNIT   { 200, 200, 400, (PRUSA_SKR_EXTRUDER_STEPS_PER_UNIT) }
  #if PRUSA_SKR_XY_STEPPERS == 2 // LDO 0.9° X/Y
    #define X_CURRENT              900
    #define X_CURRENT_HOME         300
    #define Y_CURRENT             1000
    #define Y_CURRENT_HOME         400

    // StallGuard settings
    #ifdef PRUSA_SKR_X_STALL_SENSITIVITY
      #define X_STALL_SENSITIVITY PRUSA_SKR_X_STALL_SENSITIVITY
    #else
      #define X_STALL_SENSITIVITY   81
    #endif
    #ifdef PRUSA_SKR_Y_STALL_SENSITIVITY
      #define Y_STALL_SENSITIVITY PRUSA_SKR_Y_STALL_SENSITIVITY
    #else
      #define Y_STALL_SENSITIVITY   85
    #endif

  #elif PRUSA_SKR_XY_STEPPERS == 3 // Moons 0.9° X/Y
    #define X_CURRENT              650
    #define X_CURRENT_HOME         225
    #define Y_CURRENT              750
    #define Y_CURRENT_HOME         200

    // StallGuard settings
    #ifdef PRUSA_SKR_X_STALL_SENSITIVITY
      #define X_STALL_SENSITIVITY PRUSA_SKR_X_STALL_SENSITIVITY
    #else
      #define X_STALL_SENSITIVITY  140
    #endif
    #ifdef PRUSA_SKR_Y_STALL_SENSITIVITY
      #define Y_STALL_SENSITIVITY PRUSA_SKR_Y_STALL_SENSITIVITY
    #else
      #define Y_STALL_SENSITIVITY  132
    #endif

  #endif
#endif

// Homing speeds (mm/min)
#ifndef PRUSA_SKR_HOMING_FEEDRATE_MM_M
  #define HOMING_FEEDRATE_MM_M { (50*60), (50*60), (4*60) }
#else
  #define HOMING_FEEDRATE_MM_M PRUSA_SKR_HOMING_FEEDRATE_MM_M
#endif

// X/Y Inverting Options
#if DISABLED(PRUSA_SKR_INVERT_X_DIR)
  #define INVERT_X_DIR  false
#else
  #define INVERT_X_DIR   true
#endif
#if DISABLED(PRUSA_SKR_INVERT_Y_DIR)
  #define INVERT_Y_DIR   true
#else
  #define INVERT_Y_DIR  false
#endif

//===========================================================================
//================================= Hotend ==================================
//===========================================================================

/**
 * Extruder
 *
 * Bear Extruder is enabled by default.
 *
 * Options:   1: Bear extruder w/ PINDA V2 or SuperPINDA
 *            2: Bear extruder w/ integrated BLTouch mount by Vertigo 235 https://www.prusaprinters.org/prints/6606
 *            3: Bondtech BMG extruder w/ PINDA V2 or SuperPINDA https://www.bondtech.se/en/product/prusa-i3-mk3s-extruder-upgrade/
 *            4: Bondtech BMG extruder w/ BLTouch mount by Vertigo 235 https://www.prusaprinters.org/prints/6623
 */
#if !defined(PRUSA_SKR_EXTRUDER) || (PRUSA_SKR_EXTRUDER < 1 || PRUSA_SKR_EXTRUDER > 4)
  #error "PRUSA_SKR_EXTRUDER is invalid or not defined."
#elif PRUSA_SKR_EXTRUDER == 2 || PRUSA_SKR_EXTRUDER == 4 // Bear or Bondtech BMG extruder with BLTouch
  #define BLTOUCH
  #define TEMP_SENSOR_PROBE           0
  #define PROBING_MARGIN              5
  #define Z_CLEARANCE_DEPLOY_PROBE    5
  #define Z_CLEARANCE_BETWEEN_PROBES  3
  #define Z_CLEARANCE_MULTI_PROBE     3
  //#define Z_STEPPER_ALIGN_XY { { 10, 105 }, { 220, 105 } }    // Use default locations?

  #ifdef PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
    #define NOZZLE_TO_PROBE_OFFSET PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
  #elif PRUSA_SKR_EXTRUDER == 2 // Bear Extruder w/ integrated BLTouch mount
    #define NOZZLE_TO_PROBE_OFFSET { 26.71, 2.298, 0 } // Pulled from https://www.thingiverse.com/thing:3251530/comments#comment-2915938
  #elif PRUSA_SKR_EXTRUDER == 4 // Bondtech BMG Extruder w/ BLTouch mount
    #define NOZZLE_TO_PROBE_OFFSET { -24.3, -34.1, 0 } // Pulled from https://www.thingiverse.com/thing:3864666/comments#comment-2882122
  #endif

#elif PRUSA_SKR_EXTRUDER == 1 || PRUSA_SKR_EXTRUDER == 3 // Bear or Bondtech BMG extruder with PINDA V2/SuperPINDA

  #if !defined(PRUSA_SKR_PINDA_PROBE) || (PRUSA_SKR_PINDA_PROBE < 1 || PRUSA_SKR_PINDA_PROBE > 2 )
    #error "PRUSA_SKR_PINDA_PROBE is invalid or not defined."
  #elif PRUSA_SKR_PINDA_PROBE == 1 // PINDA V2
    #define TEMP_SENSOR_PROBE         1
  #elif PRUSA_SKR_PINDA_PROBE == 2 // SuperPINDA
    #define TEMP_SENSOR_PROBE         0
  #endif

  #define FIX_MOUNTED_PROBE

  #ifdef PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
    #define NOZZLE_TO_PROBE_OFFSET PRUSA_SKR_NOZZLE_TO_PROBE_OFFSET
  #else
    #define NOZZLE_TO_PROBE_OFFSET { 23, 5, 0 }
  #endif

  #define PROBING_MARGIN             10
  #define Z_CLEARANCE_DEPLOY_PROBE    0
  #define Z_CLEARANCE_BETWEEN_PROBES  2
  #define Z_CLEARANCE_MULTI_PROBE     2
  #define PROBING_HEATERS_OFF
  #define Z_STEPPER_ALIGN_XY { { 40, 90 }, { 230,  90 } }
#endif

//===========================================================================
//========================= Thermal & PID Settings ==========================
//===========================================================================

/**
 * Thermistor
 *
 * Stock E3D Semitec 104NT-4-R025H42G/104GT-2 thermistor is enabled by default.
 *
 * Options:  1: E3D Semitec 104NT-4-R025H42G/104GT-2
 *           2: Slice Engineering's 450°C High Temperature thermistor
 *              !WARNING! If you plan to print above 295°C, you will need to upgrade from the stock V6 aluminum block or it will soften and/or melt!
 */
#if !defined(PRUSA_SKR_THERMISTOR) || (PRUSA_SKR_THERMISTOR < 1 || PRUSA_SKR_THERMISTOR > 2)
  #error "PRUSA_SKR_THERMISTOR is invalid or not defined."
#elif PRUSA_SKR_THERMISTOR == 1
  #define TEMP_SENSOR_0   5
  #define HEATER_0_MAXTEMP 310 // 295 + 15
#elif PRUSA_SKR_THERMISTOR == 2
  #define TEMP_SENSOR_0  67
  #define HEATER_0_MAXTEMP 455 // 450 + 15
#endif

/**
 * PID Settings
 *
 * Stock E3D V6 hotend and Prusa MK52 bed PID settings are enabled by default.
 */
#if ENABLED(PRUSA_SKR_CUSTOM_HOTEND_PID) && (!defined(PRUSA_SKR_DEFAULT_Kp) || !defined(PRUSA_SKR_DEFAULT_Ki) || !defined(PRUSA_SKR_DEFAULT_Kd))
  #error "PRUSA_SKR_DEFAULT_Kp, PRUSA_SKR_DEFAULT_Ki, or PRUSA_SKR_DEFAULT_Kd are invalid or not defined."
#elif ENABLED(PRUSA_SKR_CUSTOM_HOTEND_PID) && (defined(PRUSA_SKR_DEFAULT_Kp) && defined(PRUSA_SKR_DEFAULT_Ki) && defined(PRUSA_SKR_DEFAULT_Kd))
  #define DEFAULT_Kp PRUSA_SKR_DEFAULT_Kp
  #define DEFAULT_Ki PRUSA_SKR_DEFAULT_Ki
  #define DEFAULT_Kd PRUSA_SKR_DEFAULT_Kd
#else
  #define DEFAULT_Kp  16.50
  #define DEFAULT_Ki   1.16
  #define DEFAULT_Kd  58.80
#endif

#if ENABLED(PRUSA_SKR_CUSTOM_BED_PID) && (!defined(PRUSA_SKR_DEFAULT_bedKp) || !defined(PRUSA_SKR_DEFAULT_bedKi) || !defined(PRUSA_SKR_DEFAULT_bedKd))
  #error "PRUSA_SKR_DEFAULT_bedKp, PRUSA_SKR_DEFAULT_bedKi, or PRUSA_SKR_DEFAULT_bedKd are invalid or not defined."
#elif ENABLED(PRUSA_SKR_CUSTOM_BED_PID) && (defined(PRUSA_SKR_DEFAULT_bedKp) && defined(PRUSA_SKR_DEFAULT_bedKi) && defined(PRUSA_SKR_DEFAULT_bedKd))
  #define DEFAULT_bedKp PRUSA_SKR_DEFAULT_bedKp
  #define DEFAULT_bedKi PRUSA_SKR_DEFAULT_bedKi
  #define DEFAULT_bedKd PRUSA_SKR_DEFAULT_bedKd
#else
  #define DEFAULT_bedKp  28.13
  #define DEFAULT_bedKi   2.09
  #define DEFAULT_bedKd 483.07
#endif

//===========================================================================
//============================ Part Cooling Fan =============================
//===========================================================================

/**
 * Part Cooling Fan
 *
 * Mechatronics B5015E24B-BSR 5015 fan is enabled by default
 *
 * Options:  1: Mechatronics B5015E24B-BSR 5015 fan   // https://www.digikey.com/en/products/detail/mechatronics-fan-group/B5015E24B-BSR/5209731
 *           2: Delta BFB0524HH 5015 fan              // https://www.digikey.com/en/products/detail/delta-electronics/bfb0524hh/1014447
 */
#if !defined(PRUSA_SKR_PART_COOLING_FAN) || (PRUSA_SKR_PART_COOLING_FAN < 1 || PRUSA_SKR_PART_COOLING_FAN > 2)
  #error "PRUSA_SKR_PART_COOLING_FAN is invalid or not defined."
#elif PRUSA_SKR_PART_COOLING_FAN == 1
  #define FAN_MIN_PWM 80
#elif PRUSA_SKR_PART_COOLING_FAN == 2
  #define FAN_MIN_PWM 20
#endif

//===========================================================================
//============================= Filament Runout =============================
//===========================================================================

// If filament runout is throwing false alarms, uncomment & increase this value.
// This is NOT the same as FILAMENT_RUNOUT_DISTANCE_MM. See FILAMENT_RUNOUT_DISTANCE_MM in Configuration.h for more info.

//#define FILAMENT_RUNOUT_THRESHOLD 5

// Should this setting be exposed to users?

//===========================================================================
//============================== Bed Leveling ===============================
//===========================================================================

// Bilinear is enabled by default.

/**
 * Options:  1: Bilinear
 *           2: Unified Bed Leveling
 */
#if !defined(PRUSA_SKR_BED_LEVELING) || (PRUSA_SKR_BED_LEVELING < 1 || PRUSA_SKR_BED_LEVELING > 2)
  #error "PRUSA_SKR_BED_LEVELING is invalid or not defined."
#elif PRUSA_SKR_BED_LEVELING == 1
  #define AUTO_BED_LEVELING_BILINEAR
  #define HOTEND_IDLE_TIMEOUT_SEC (5*60)
#elif PRUSA_SKR_BED_LEVELING == 2
  #define AUTO_BED_LEVELING_UBL
  #define HOTEND_IDLE_TIMEOUT_SEC (15*60) // Longer timeout due to increased probe time
#endif

//===========================================================================
//================================= Display =================================
//===========================================================================

// Stock/OLED RepRapDiscount smart controller is enabled by default.

/**
 * Options:  1: Stock/OLED RepRapDiscount smart controller
 *           2: BigTreeTech Dual Mode TFT (TFT35/TFT50/TFT70,etc.)
 */
#if !defined(PRUSA_SKR_DISPLAY) || (PRUSA_SKR_DISPLAY < 1 || PRUSA_SKR_DISPLAY > 2)
  #error "PRUSA_SKR_DISPLAY is invalid or not defined."
#elif PRUSA_SKR_DISPLAY == 1
  #define REPRAP_DISCOUNT_SMART_CONTROLLER
  #define LCD_INFO_SCREEN_STYLE 1
#elif PRUSA_SKR_DISPLAY == 2
  #if PRUSA_SKR_BED_LEVELING == 2 // Requires UBL
    #define MESH_EDIT_GFX_OVERLAY
  #endif
  #define REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
  #define BOOT_MARLIN_LOGO_ANIMATED
  #define BABYSTEP_ZPROBE_GFX_OVERLAY
#endif

/**
 * LCD Language
 *
 * English is enabled by default:
 *
 * Options:  1: English                  12: Finnish                 23: Portuguese
 *           2: Aragonese                13: French                  24: Portuguese (Brazilian)
 *           3: Basque-Euskera           14: Galician                25: Romanian
 *           4: Bulgarian                15: German                  26: Russian
 *           5: Catalan                  16: Greek                   27: Slovak
 *           6: Chinese (Simplified)     17: Greek (Greece)          28: Spanish
 *           7: Chinese (Traditional)    18: Hungarian               29: Swedish
 *           8: Croatian                 19: Italian                 30: Turkish
 *           9: Czech                    20: Japanese                31: Ukrainian
 *           10: Danish                  21: Korean (South Korea)    32: Vietnamese
 *           11: Dutch                   22: Polish
 */
#if !defined(PRUSA_SKR_LCD_LANGUAGE) || (PRUSA_SKR_LCD_LANGUAGE < 1 || PRUSA_SKR_LCD_LANGUAGE > 32)
  #error "PRUSA_SKR_LCD_LANGUAGE is invalid or not defined."
#elif PRUSA_SKR_LCD_LANGUAGE == 1   // English
  #define LCD_LANGUAGE en
#elif PRUSA_SKR_LCD_LANGUAGE == 2   // Aragonese
  #define LCD_LANGUAGE an
#elif PRUSA_SKR_LCD_LANGUAGE == 3   // Basque-Euskera
  #define LCD_LANGUAGE eu
#elif PRUSA_SKR_LCD_LANGUAGE == 4   // Bulgarian
  #define LCD_LANGUAGE bg
#elif PRUSA_SKR_LCD_LANGUAGE == 5   // Catalan
  #define LCD_LANGUAGE ca
#elif PRUSA_SKR_LCD_LANGUAGE == 6   // Chinese (Simplified)
  #define LCD_LANGUAGE zh_CN
#elif PRUSA_SKR_LCD_LANGUAGE == 7   // Chinese (Traditional)
  #define LCD_LANGUAGE zh_TW
#elif PRUSA_SKR_LCD_LANGUAGE == 8   // Croatian
  #define LCD_LANGUAGE hr
#elif PRUSA_SKR_LCD_LANGUAGE == 9   // Czech
  #define LCD_LANGUAGE cz
#elif PRUSA_SKR_LCD_LANGUAGE == 10  // Danish
  #define LCD_LANGUAGE da
#elif PRUSA_SKR_LCD_LANGUAGE == 11  // Dutch
  #define LCD_LANGUAGE nl
#elif PRUSA_SKR_LCD_LANGUAGE == 12  // Finnish
  #define LCD_LANGUAGE fi
#elif PRUSA_SKR_LCD_LANGUAGE == 13  // French
  #define LCD_LANGUAGE fr
#elif PRUSA_SKR_LCD_LANGUAGE == 14  // Galician
  #define LCD_LANGUAGE gl
#elif PRUSA_SKR_LCD_LANGUAGE == 15  // German
  #define LCD_LANGUAGE de
#elif PRUSA_SKR_LCD_LANGUAGE == 16  // Greek
  #define LCD_LANGUAGE el
#elif PRUSA_SKR_LCD_LANGUAGE == 17  // Greek (Greece)
  #define LCD_LANGUAGE el_gr
#elif PRUSA_SKR_LCD_LANGUAGE == 18  // Hungarian
  #define LCD_LANGUAGE hu
#elif PRUSA_SKR_LCD_LANGUAGE == 19  // Italian
  #define LCD_LANGUAGE it
#elif PRUSA_SKR_LCD_LANGUAGE == 20  // Japanese
  #define LCD_LANGUAGE jp_kana
#elif PRUSA_SKR_LCD_LANGUAGE == 21  // Korean (South Korea)
  #define LCD_LANGUAGE ko_KR
#elif PRUSA_SKR_LCD_LANGUAGE == 22  // Polish
  #define LCD_LANGUAGE pl
#elif PRUSA_SKR_LCD_LANGUAGE == 23  // Portuguese
  #define LCD_LANGUAGE pt
#elif PRUSA_SKR_LCD_LANGUAGE == 24  // Portuguese (Brazilian)
  #define LCD_LANGUAGE pt_br
#elif PRUSA_SKR_LCD_LANGUAGE == 25  // Romanian
  #define LCD_LANGUAGE ro
#elif PRUSA_SKR_LCD_LANGUAGE == 26  // Russian
  #define LCD_LANGUAGE ru
#elif PRUSA_SKR_LCD_LANGUAGE == 27  // Slovak
  #define LCD_LANGUAGE sk
#elif PRUSA_SKR_LCD_LANGUAGE == 28  // Spanish
  #define LCD_LANGUAGE es
#elif PRUSA_SKR_LCD_LANGUAGE == 29  // Swedish
  #define LCD_LANGUAGE sv
#elif PRUSA_SKR_LCD_LANGUAGE == 30  // Turkish
  #define LCD_LANGUAGE tr
#elif PRUSA_SKR_LCD_LANGUAGE == 31  // Ukrainian
  #define LCD_LANGUAGE uk
#elif PRUSA_SKR_LCD_LANGUAGE == 32  // Vietnamese
  #define LCD_LANGUAGE vi
#endif

//===========================================================================
//================================ NeoPixels ================================
//===========================================================================

// NeoPixels are disabled by default.

#if ENABLED(PRUSA_SKR_NEOPIXELS)
  #define NEOPIXEL_LED
  #define LED_CONTROL_MENU

  /**
   * NeoPixel Type
   *
   * Options:  1: Red, Green, Blue          (NEO_GRB)
   *           2: Red, Green, Blue, White   (NEO_GRBW)
   */
  #if defined(PRUSA_SKR_NEOPIXEL_TYPE) && (PRUSA_SKR_NEOPIXEL_TYPE < 1 || PRUSA_SKR_NEOPIXEL_TYPE > 2)
    #error "PRUSA_SKR_NEOPIXEL_TYPE is invalid or not defined."
  #elif PRUSA_SKR_NEOPIXEL_TYPE == 1
    #define NEOPIXEL_TYPE NEO_GRB
  #elif PRUSA_SKR_NEOPIXEL_TYPE == 2
    #define NEOPIXEL_TYPE NEO_GRBW
  #endif

  #ifdef PRUSA_SKR_NEOPIXEL_PIXELS
    #define NEOPIXEL_PIXELS PRUSA_SKR_NEOPIXEL_PIXELS
  #else
    #define NEOPIXEL_PIXELS 17
  #endif
  #ifdef PRUSA_SKR_NEOPIXEL_BRIGHTNESS
    #define NEOPIXEL_BRIGHTNESS PRUSA_SKR_NEOPIXEL_BRIGHTNESS
  #else
    #define NEOPIXEL_BRIGHTNESS 255
  #endif
#endif
